version: '3'

services:
  kms:
    container_name: pykms
    image: ghcr.io/py-kms-organization/py-kms:python3-next
    ports:
      - 1688:1688
    environment:
      - IP=0.0.0.0
      - SQLITE=true
      - HWID=RANDOM
      - LOGLEVEL=INFO
    restart: always
    volumes:
      - /mnt/nfs/docker/pykms/db:/home/py-kms/db
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.rule=Host(`{{container_name}}.{{traefik_domain}}`)"
      - "traefik.http.routers.librespeed.entrypoints=https"
      - "traefik.http.routers.librespeed.tls.certresolver=cloudflare"

networks:
  traefik:
    external: true